import { createFileRoute } from "@tanstack/react-router";
import { ContentPage } from "@/components/site/ContentPage";

export const Route = createFileRoute("/privacy")({
  head: () => ({
    meta: [
      { title: "Privacy Policy — Soniccora" },
      {
        name: "description",
        content:
          "This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service.",
      },
      { property: "og:title", content: "Soniccora Privacy Policy" },
      {
        property: "og:description",
        content: "How we collect, use and protect your personal data.",
      },
    ],
  }),
  component: () => (
    <ContentPage
      eyebrow="PRIVACY"
      title="Privacy Policy"
      intro={
        <div className="space-y-4">
          <p>Last updated: April 27, 2026</p>
          <p>This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.</p>
          <p>We use Your Personal Data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy. This Privacy Policy has been created with the help of the <a href="https://www.termsfeed.com/privacy-policy-generator/" target="_blank" className="text-primary hover:underline">Privacy Policy Generator</a>.</p>
        </div>
      }
      sections={[
        {
          heading: "Interpretation and Definitions",
          body: (
            <div className="space-y-6">
              <div>
                <h3 className="text-xl font-semibold text-foreground mb-3">Interpretation</h3>
                <p>The words whose initial letters are capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.</p>
              </div>
              <div>
                <h3 className="text-xl font-semibold text-foreground mb-3">Definitions</h3>
                <p>For the purposes of this Privacy Policy:</p>
                <ul className="list-disc pl-5 mt-4 space-y-4">
                  <li>
                    <p><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</p>
                  </li>
                  <li>
                    <p><strong>Affiliate</strong> means an entity that controls, is controlled by, or is under common control with a party, where &quot;control&quot; means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</p>
                  </li>
                  <li>
                    <p><strong>Company</strong> (referred to as either &quot;the Company&quot;, &quot;We&quot;, &quot;Us&quot; or &quot;Our&quot; in this Privacy Policy) refers to Soniccora Technologies Inc.</p>
                  </li>
                  <li>
                    <p><strong>Cookies</strong> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</p>
                  </li>
                  <li>
                    <p><strong>Country</strong> refers to: California, United States</p>
                  </li>
                  <li>
                    <p><strong>Device</strong> means any device that can access the Service such as a computer, a cell phone or a digital tablet.</p>
                  </li>
                  <li>
                    <p><strong>Personal Data</strong> (or &quot;Personal Information&quot;) is any information that relates to an identified or identifiable individual.</p>
                    <p className="mt-2 text-sm text-foreground/60">We use &quot;Personal Data&quot; and &quot;Personal Information&quot; interchangeably unless a law uses a specific term.</p>
                  </li>
                  <li>
                    <p><strong>Service</strong> refers to the Website.</p>
                  </li>
                  <li>
                    <p><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.</p>
                  </li>
                  <li>
                    <p><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</p>
                  </li>
                  <li>
                    <p><strong>Website</strong> refers to soniccora, accessible from <a href="https://www.soniccora.com/" className="text-primary hover:underline" rel="external nofollow noopener" target="_blank">https://www.soniccora.com/</a>.</p>
                  </li>
                  <li>
                    <p><strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</p>
                  </li>
                </ul>
              </div>
            </div>
          ),
        },
        {
          heading: "Collecting and Using Your Personal Data",
          body: (
            <div className="space-y-8">
              <div>
                <h3 className="text-xl font-semibold text-foreground mb-4">Types of Data Collected</h3>
                <div className="space-y-4">
                  <h4 className="font-semibold text-foreground/90">Personal Data</h4>
                  <p>While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:</p>
                  <ul className="list-disc pl-5 space-y-2">
                    <li>Email address</li>
                    <li>First name and last name</li>
                    <li>Phone number</li>
                    <li>Address, State, Province, ZIP/Postal code, City</li>
                  </ul>
                </div>

                <div className="mt-8 space-y-4">
                  <h4 className="font-semibold text-foreground/90">Usage Data</h4>
                  <p>Usage Data is collected automatically when using the Service.</p>
                  <p>Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.</p>
                  <p>When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device's unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.</p>
                  <p>We may also collect information that Your browser sends whenever You visit Our Service or when You access the Service by or through a mobile device.</p>
                </div>

                <div className="mt-8 space-y-4">
                  <h4 className="font-semibold text-foreground/90">Tracking Technologies and Cookies</h4>
                  <p>We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies We use include beacons, tags, and scripts to collect and track information and to improve and analyze Our Service. The technologies We use may include:</p>
                  <ul className="list-disc pl-5 space-y-3">
                    <li><strong>Cookies or Browser Cookies.</strong> A cookie is a small file placed on Your Device. You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of our Service.</li>
                    <li><strong>Web Beacons.</strong> Certain sections of our Service and our emails may contain small electronic files known as web beacons (also referred to as clear gifs, pixel tags, and single-pixel gifs) that permit the Company, for example, to count users who have visited those pages or opened an email and for other related website statistics.</li>
                  </ul>
                  <p>Cookies can be &quot;Persistent&quot; or &quot;Session&quot; Cookies. Persistent Cookies remain on Your personal computer or mobile device when You go offline, while Session Cookies are deleted as soon as You close Your web browser.</p>
                  <p>Where required by law, we use non-essential cookies (such as analytics, advertising, and remarketing cookies) only with Your consent. You can withdraw or change Your consent at any time using Our cookie preferences tool (if available) or through Your browser/device settings. Withdrawing consent does not affect the lawfulness of processing based on consent before its withdrawal.</p>
                  <p>We use both Session and Persistent Cookies for the purposes set out below:</p>
                  <ul className="list-disc pl-5 space-y-4">
                    <li>
                      <p><strong>Necessary / Essential Cookies</strong></p>
                      <p className="text-sm opacity-80">Type: Session Cookies | Administered by: Us</p>
                      <p className="mt-1">Purpose: These Cookies are essential to provide You with services available through the Website and to enable You to use some of its features. They help to authenticate users and prevent fraudulent use of user accounts. Without these Cookies, the services that You have asked for cannot be provided, and We only use these Cookies to provide You with those services.</p>
                    </li>
                    <li>
                      <p><strong>Cookies Policy / Notice Acceptance Cookies</strong></p>
                      <p className="text-sm opacity-80">Type: Persistent Cookies | Administered by: Us</p>
                      <p className="mt-1">Purpose: These Cookies identify if users have accepted the use of cookies on the Website.</p>
                    </li>
                    <li>
                      <p><strong>Functionality Cookies</strong></p>
                      <p className="text-sm opacity-80">Type: Persistent Cookies | Administered by: Us</p>
                      <p className="mt-1">Purpose: These Cookies allow Us to remember choices You make when You use the Website, such as remembering your login details or language preference. The purpose of these Cookies is to provide You with a more personal experience and to avoid You having to re-enter your preferences every time You use the Website.</p>
                    </li>
                  </ul>
                </div>
              </div>

              <div>
                <h3 className="text-xl font-semibold text-foreground mb-4">Use of Your Personal Data</h3>
                <p>The Company may use Personal Data for the following purposes:</p>
                <ul className="list-disc pl-5 mt-4 space-y-4">
                  <li><strong>To provide and maintain our Service</strong>, including to monitor the usage of our Service.</li>
                  <li><strong>To manage Your Account:</strong> to manage Your registration as a user of the Service. The Personal Data You provide can give You access to different functionalities of the Service that are available to You as a registered user.</li>
                  <li><strong>For the performance of a contract:</strong> the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased or of any other contract with Us through the Service.</li>
                  <li><strong>To contact You:</strong> To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as a mobile application's push notifications regarding updates or informative communications related to the functionalities, products or contracted services, including the security updates, when necessary or reasonable for their implementation.</li>
                  <li><strong>To provide You</strong> with news, special offers, and general information about other goods, services and events which We offer that are similar to those that you have already purchased or inquired about unless You have opted not to receive such information.</li>
                  <li><strong>To manage Your requests:</strong> To attend and manage Your requests to Us.</li>
                  <li><strong>For business transfers:</strong> We may use Your Personal Data to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of Our assets, whether as a going concern or as part of bankruptcy, liquidation, or similar proceeding, in which Personal Data held by Us about our Service users is among the assets transferred.</li>
                  <li><strong>For other purposes</strong>: We may use Your information for other purposes, such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns and to evaluate and improve our Service, products, services, marketing and your experience.</li>
                </ul>

                <p className="mt-6">We may share Your Personal Data in the following situations:</p>
                <ul className="list-disc pl-5 mt-4 space-y-3">
                  <li><strong>With Service Providers:</strong> We may share Your Personal Data with Service Providers to monitor and analyze the use of our Service, to contact You.</li>
                  <li><strong>For business transfers:</strong> We may share or transfer Your Personal Data in connection with, or during negotiations of, any merger, sale of Company assets, financing, or acquisition of all or a portion of Our business to another company.</li>
                  <li><strong>With Affiliates:</strong> We may share Your Personal Data with Our affiliates, in which case we will require those affiliates to honor this Privacy Policy. Affiliates include Our parent company and any other subsidiaries, joint venture partners or other companies that We control or that are under common control with Us.</li>
                  <li><strong>With business partners:</strong> We may share Your Personal Data with Our business partners to offer You certain products, services or promotions.</li>
                  <li><strong>With other users:</strong> If Our Service offers public areas, when You share Personal Data or otherwise interact in the public areas with other users, such information may be viewed by all users and may be publicly distributed outside.</li>
                  <li><strong>With Your consent</strong>: We may disclose Your Personal Data for any other purpose with Your consent.</li>
                </ul>
              </div>

              <div>
                <h3 className="text-xl font-semibold text-foreground mb-4">Retention of Your Personal Data</h3>
                <p>The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations (for example, if We are required to retain Your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.</p>
                <p className="mt-4">Where possible, We apply shorter retention periods and/or reduce identifiability by deleting, aggregating, or anonymizing data. Unless otherwise stated, the retention periods below are maximum periods (&quot;up to&quot;) and We may delete or anonymize data sooner when it is no longer needed for the relevant purpose. We apply different retention periods to different categories of Personal Data based on the purpose of processing and legal obligations:</p>
                <ul className="list-disc pl-5 mt-4 space-y-4">
                  <li>
                    <p><strong>Account Information</strong></p>
                    <ul className="list-circle pl-5 mt-1">
                      <li>User Accounts: retained for the duration of your account relationship plus up to 24 months after account closure to handle any post-termination issues or resolve disputes.</li>
                    </ul>
                  </li>
                  <li>
                    <p><strong>Customer Support Data</strong></p>
                    <ul className="list-circle pl-5 mt-1 space-y-1">
                      <li>Support tickets and correspondence: up to 24 months from the date of ticket closure.</li>
                      <li>Chat transcripts: up to 24 months for quality assurance and staff training purposes.</li>
                    </ul>
                  </li>
                  <li>
                    <p><strong>Usage Data</strong></p>
                    <ul className="list-circle pl-5 mt-1 space-y-1">
                      <li>Website analytics data (cookies, IP addresses, device identifiers): up to 24 months from the date of collection.</li>
                      <li>Server logs (IP addresses, access times): up to 24 months for security monitoring and troubleshooting purposes.</li>
                    </ul>
                  </li>
                </ul>
                <p className="mt-4">We may retain Personal Data beyond the periods stated above for legal obligations, legal claims, Your explicit request, or technical limitations.</p>
              </div>

              <div>
                <h3 className="text-xl font-semibold text-foreground mb-4">Transfer of Your Personal Data</h3>
                <p>Your information, including Personal Data, is processed at the Company's operating offices and in any other places where the parties involved in the processing are located. It means that this information may be transferred to — and maintained on — computers located outside of Your state, province, country or other governmental jurisdiction where the data protection laws may differ from those from Your jurisdiction.</p>
              </div>

              <div>
                <h3 className="text-xl font-semibold text-foreground mb-4">Delete Your Personal Data</h3>
                <p>You have the right to delete or request that We assist in deleting the Personal Data that We have collected about You.</p>
                <p className="mt-2">Our Service may give You the ability to delete certain information about You from within the Service. You may update, amend, or delete Your information at any time by signing in to Your Account and visiting the account settings section. You may also contact Us to request access to, correct, or delete any Personal Data that You have provided to Us.</p>
              </div>
            </div>
          ),
        },
        {
          heading: "Detailed Information on Processing",
          body: (
            <div className="space-y-6">
              <p>The Service Providers We use may have access to Your Personal Data. These third-party vendors collect, store, use, process and transfer information about Your activity on Our Service in accordance with their Privacy Policies.</p>
              <div>
                <h3 className="text-lg font-semibold mb-3">Usage, Performance and Miscellaneous</h3>
                <ul className="list-disc pl-5 space-y-4">
                  <li>
                    <p><strong>Mouseflow</strong></p>
                    <p className="text-sm opacity-80">Mouseflow is a session replay and heatmap tool. The service is operated by ApS.</p>
                    <p className="mt-1">Privacy Policy: <a href="https://mouseflow.com/privacy/" className="text-primary hover:underline" target="_blank">https://mouseflow.com/privacy/</a></p>
                  </li>
                  <li>
                    <p><strong>FreshDesk</strong></p>
                    <p className="text-sm opacity-80">FreshDesk is a customer support software. The service is operated by Freshworks, Inc.</p>
                    <p className="mt-1">Privacy Policy: <a href="https://www.freshworks.com/privacy/" className="text-primary hover:underline" target="_blank">https://www.freshworks.com/privacy/</a></p>
                  </li>
                  <li>
                    <p><strong>Google Places</strong></p>
                    <p className="text-sm opacity-80">Google Places returns information about places using HTTP requests. It is operated by Google.</p>
                    <p className="mt-1">Privacy Policy: <a href="https://www.google.com/intl/en/policies/privacy/" className="text-primary hover:underline" target="_blank">https://www.google.com/intl/en/policies/privacy/</a></p>
                  </li>
                </ul>
              </div>
            </div>
          ),
        },
        {
          heading: "Children's Privacy",
          body: (
            <p>Our Service does not address anyone under the age of 16. We do not knowingly collect personally identifiable information from anyone under the age of 16. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us. If We become aware that We have collected Personal Data from anyone under the age of 16 without verification of parental consent, We take steps to remove that information from Our servers.</p>
          ),
        },
        {
          heading: "Links to Other Websites",
          body: (
            <p>Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party's site. We strongly advise You to review the Privacy Policy of every site You visit. We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.</p>
          ),
        },
        {
          heading: "Changes to this Privacy Policy",
          body: (
            <p>We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page. We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming effective and update the &quot;Last updated&quot; date at the top of this Privacy Policy.</p>
          ),
        },
        {
          heading: "Contact Us",
          body: (
            <div className="space-y-4">
              <p>If you have any questions about this Privacy Policy, You can contact us:</p>
              <ul className="list-disc pl-5 space-y-2">
                <li>By email: connect@soniccora.com</li>
                <li>By visiting this page on our website: <a href="https://www.soniccora.com/contact" className="text-primary hover:underline" target="_blank">https://www.soniccora.com/contact</a></li>
                <li>By phone: +1 (213) 555-7812</li>
                <li>By mail: 447 S Spring St, Los Angeles, CA 90013, USA</li>
              </ul>
            </div>
          ),
        },
      ]}
      ctaHref="/product"
      ctaLabel="Back to Platform"
      showCTA={false}
    />
  ),
});
